### PR TITLE
Cli backwards compatibility

### LINKED ISSUE #259: Support backward compatibility with new cli maven plugin
Moving `helidon:dev` to `helidon-cli:dev` (issue #247) will break older CLI versions (`< 2.0.3`).
 Older CLI that refresh their metadata should not use the newest version of `helidon-maven-plugin`,
 otherwise invocations of `helidon:dev` will fail.

In order to fix the version of `helidon-maven-plugin` for older versions of the CLI, we will
 update the metadata to deprecate `build-tools.version` and introduce a new property `cli.{version}.plugin.version`.

The value of `build-tools.version` will remain untouched and contain the current version of `helidon-maven-plugin`.

The new property `cli.{version}.plugin.version` will drive the version of the new `helidon-cli-maven-plugin`, contains
 the lower bracket of the CLI version range that should use a specific version of the plugin.

```properties
# This is used by helidon cli <= 2.0.2
build-tools.version=2.0.2

# Version of the helidon-cli-maven-plugin by cli versions
# This allows to introduce backward incompatible changes in the helidon-cli-maven-plugin
cli.latest.plugin.version=2.2.0
cli.2.1.0.plugin.version=2.0.9
cli.2.0.3.plugin.version=2.0.3

# cli v2.0.1 -> helidon-maven-plugin v2.0.2
# cli v2.0.2 -> helidon-maven-plugin v2.0.2
# cli v2.0.3 -> helidon-cli-maven-plugin v2.0.3
# cli v2.0.4 -> helidon-cli-maven-plugin v2.0.3
# cli v2.0.5 -> helidon-cli-maven-plugin v2.0.3
# cli v2.1.0 -> helidon-cli-maven-plugin v2.0.9
# cli v2.1.1 -> helidon-cli-maven-plugin v2.0.9
# cli v2.1.2 -> helidon-cli-maven-plugin v2.0.9
# cli v2.2.0 -> helidon-cli-maven-plugin v2.2.0
```

### PR DESCRIPTION
**Pull request by batsatt**
Fixes #259.

### CODE REVIEW

File: utils/src/main/java/io/helidon/build/util/Constants.java [hunk 1]
```diff
@@ -31,14 +31,15 @@
     public static final OSType OS = currentOS();
 
     /**
-     * End of line string.
+     * End of line string.                                                                                                                                                                        `
```
Comment (romain-grecourt) [inline utils/src/main/java/io/helidon/build/util/Constants.java:34]: Looks like that character was not intended.

Comment (batsatt) [reply utils/src/main/java/io/helidon/build/util/Constants.java]: Ah, invisible control character; fixed.
