### PR TITLE
Fix maven executable location with homebrew maven installations.

### LINKED ISSUE #157: helidon init fails with error: /usr/local/Cellar/maven/3.6.1/lib does not exist
Version: 2.0.0-RC1

I installed Maven using `brew` on MacOS. When I run helidon init I get an error:

```
$ helidon init
error: /usr/local/Cellar/maven/3.6.1/lib does not exist
```

`mvn` works fine on its own. I don't have `MAVEN_HOME` set (if that matters). It is true, my install does not have a `lib` directory:

```
$ ls  /usr/local/Cellar/maven/3.6.1/
INSTALL_RECEIPT.json  LICENSE               NOTICE                README.txt            bin/                  libexec/
```

If I download Maven from Apache and install it myself then all works AOK.

### PR DESCRIPTION
**Pull request by romain-grecourt**
Fixes #157

### CODE REVIEW

File: utils/src/main/java/io/helidon/build/util/MavenCommand.java [hunk 1]
```diff
@@ -50,6 +50,7 @@
     private static final String MAVEN_HOME_VAR = "MAVEN_HOME";
     private static final String MVN_HOME_VAR = "MVN_HOME";
     private static final String MAVEN_CORE_PREFIX = "maven-core-";
+    private static final String MAVEN_SHIM_TARGET = "../libexec/bin/mvn";
```
Comment (batsatt) [inline utils/src/main/java/io/helidon/build/util/MavenCommand.java:53]: not sure if `..` works correctly in all envs; probably should avoid it
