### PR TITLE
Fix log level support

### LINKED ISSUE #561: port 560 to 2.x
port #560 to 2.x

### PR DESCRIPTION
**Pull request by romain-grecourt**
Backport of #560
Fixes #561

### CODE REVIEW

File: helidon-cli/harness/src/main/java/io/helidon/build/cli/harness/CommandContext.java [hunk 1]
```diff
@@ -420,23 +424,26 @@ public Verbosity verbosity() {
...
                 break;
             }
             case VERBOSE: {
-                logWriter().level(VERBOSE);
+                level = VERBOSE;
                 break;
             }
             case NORMAL: {
-                logWriter().level(INFO);
+                level = (INFO);
```
Comment (batsatt) [inline helidon-cli/harness/src/main/java/io/helidon/build/cli/harness/CommandContext.java:438]: parens?

**Review by batsatt — APPROVED** [review]

File: helidon-cli/harness/src/main/java/io/helidon/build/cli/harness/CommandContext.java (hunk 1 above)
Comment (romain-grecourt) [reply helidon-cli/harness/src/main/java/io/helidon/build/cli/harness/CommandContext.java]: Fixed.
